- name: Managing NDFC Overlays
  hosts: podX-ndfc.sdn.lab
  gather_facts: False
  vars:
    pod: X
  vars_files:
    - fabric_config.yaml
    - overlay_config.yaml

  roles:
    - role: pause
      message: "create VRFs"
    - create_vrfs
