---
# tasks file for roles/create_networks
- name: Retrieve all Networks configs from overlays data structure
  set_fact:
    networks_config: "{{ overlays | json_query ('*.networks') | list }}"
  loop: "{{ overlays.keys() }}"

- name: Create per DC Networks config files from template
  ansible.builtin.template:
    src: "{{ role_path }}/templates/networks_config.j2"
    dest: "{{ role_path }}/files/{{ fabric_name }}_networks_config.yaml"
    force: True
  loop: "{{ overlays.keys() }}"
  loop_control:
    loop_var: fabric_name
    index_var: fabric_index
    label: "Creating {{ fabric_name }}_networks_config.yaml file"

- name: Create per DC config variables from files
  set_fact:
    "{{fabric_name}}_networks_config": "{{ lookup('file', '{{ role_path }}/files/{{ fabric_name }}_networks_config.yaml') | from_yaml }}"
  loop: "{{ overlays.keys() }}"
  loop_control:
    loop_var: fabric_name
    label: "Creating {{ fabric_name }}_networks_config variable"

- name: Display overlay config
  debug:
    var: "{{fabric_name}}_networks_config"
  loop: "{{ overlays.keys() }}"
  loop_control:
    loop_var: fabric_name
    label: "Displaying {{ fabric_name }}_networks_config variable"

- name: Create Networks
  cisco.dcnm.dcnm_network:
    state: merged
    fabric: "{{ fabric_name }}"
    config:
      "{{ lookup('vars', '{{ fabric_name }}' + '_networks_config') }}"
  loop: "{{ overlays.keys() }}"
  loop_control:
    loop_var: fabric_name
    label: "Creating Networks in {{ fabric_name }} fabric"
