---
- name: "A playbook to generate a network inventory report"
  hosts: all
  connection: network_cli
  tasks:

    - name: Gather NXOS facts
      cisco.nxos.nxos_facts:
        gather_subset: 
          - interfaces
      register: facts

    - name: "Display all host variables"
      debug:
        var: facts
