---
- name: Setup POAP environment
  hosts: all
  remote_user: podX
  become: true
  gather_facts: false
  tasks:
  - name: Install required packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - isc-dhcp-server
      - tftpd-hpa
      - tftp-hpa

  - name: Set up the DHCP server
    template:
      src=dhcpd.conf.j2
      dest=/etc/dhcp/dhcpd.conf
      owner=root
      group=root
      mode=0644

  - name: Restart the DHCP serer
    service:
      name=isc-dhcp-server.service
      state=restarted
      enabled=yes

  - name: Check DHCP server state
    systemd:
      name: isc-dhcp-server.service
    register: dhcp_service_state

  - name: Output DHCP service state
    debug:
      msg: 'DHCP State: {{ dhcp_service_state.status.ActiveState }}'

  - name: Stop if DHCP service is not running
    fail:
      msg: "The DHCP server failed to start"
    when: dhcp_service_state.status.ActiveState != "active"

  - name: Create TFTPD directory symlink
    file:
      src: "/srv/tftp"
      dest: "/tftpboot"
      state: link

  - name: Copy POAP script to TFTP folder
    template:
      src=poap_nexus_script.j2
      dest=/tftpboot/poap_nexus_script.py
      owner=root
      group=root
      mode=0644

  - name: Copy MD5 updater
    template:
      src=recalc.md5.sh
      dest=/tftpboot/recalc.md5.sh
      owner=root
      group=root
      mode=0755

  - name: Update MD5 on POAP script
    script: /tftpboot/recalc.md5.sh
      chdir=/tftpboot

  - name: Generate initial configs for switches
    template:
      src=switch.cfg.j2
      dest=/tftpboot/conf_{{ item.mac_address.upper()|replace(':','') }}.cfg
      owner=root
      group=root
      mode=0644
    with_items: "{{ dhcp_hosts }}"
