---
- name: "Playbook to make switch configurations"
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: no
  tasks:

    - name: "Create additional loopback interface"
      cisco.nxos.nxos_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "[Configured by Ansible]"
            enabled: true
      loop: "{{ loopbacks }}"

    - name: "Configure IP address on additional loopback interfaces"
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ip_address }}"
      loop: "{{ loopbacks }}"
