overlays:
  # DC1:
  "{{ lookup('env', 'NDFC_DC') }}":
    vrfs:
      VRF11:
        vrf_name: VRF11
        vrf_id: 50011
        attach:
          - LEAF1
          - LEAF2
      VRF12:
        vrf_name: VRF12
        attach:
          - LEAF1

    # networks:
    #   NET11:
    #     network_name: NET11
    #     network_id: 30011
    #     vrf_name: VRF11
    #     gw_ip_subnet: "10.1{{ pod }}.191.254/24"
    #     deploy: False
    #     attach:
    #       - switch: LEAF1
    #         ports: 
    #         - Ethernet1/3          
    #       - switch: LEAF2
    #         ports: 
    #         - Ethernet1/3          
    #   NET12:
    #     network_name: NET12
    #     network_id: 30012
    #     is_l2only: True
    #     deploy: False
    #     attach:
    #       - switch: LEAF1
    #         ports: 
    #         - none 
