- name: Managing NDFC fabrics
  hosts: podX-ndfc.sdn.lab
  gather_facts: False
  vars:
    pod: X
  vars_files:
    - fabric_config.yaml

  roles:
    - create_fabrics
    - role: pause
      message: "onboard switches"
    - onboard_switches