---
- name: Check NDFC fabrics
  hosts: podX-ndfc.sdn.lab
  gather_facts: False
  tasks:
    - name: REST GET fabrics
      cisco.dcnm.dcnm_rest:
        method: GET
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics"
      register: rest_fabric_list

    - name: Process fabric data
      set_fact:
        active_fabrics: "{{ rest_fabric_list.response.DATA | json_query(mq1) | to_json }}"
      vars:
        mq1: "[*].{FabricName: fabricName}"

    - name: Print active fabrics
      debug:
        var: active_fabrics
